version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx2048m
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.14.3
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic
#      - ELASTICSEARCH_PASSWORD=elastic
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch

volumes:
  esdata: